# Generated by Django 4.0.4 on 2022-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='A6UGNV2ZP7KN3YNJREE7U26YXDKSV72M', max_length=20),
        ),
    ]
