# Generated by Django 4.0.4 on 2022-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='GJNYLI63ZKO6OMO55T2J674Y74REGV2Q', max_length=20),
        ),
    ]
