# Generated by Django 4.0.4 on 2022-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='UJ7V2OKTVCQ7IUSDGLVYXNI6EOUMRWNL', max_length=32),
        ),
    ]
