# Generated by Django 4.0.4 on 2022-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='6WY3G7WEX2EGRA2MLVAAZSISCIAZP43O', max_length=32),
        ),
    ]
