# Generated by Django 4.0.4 on 2022-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='NAXBQM76L7ESUFKSUM6BXVMXXE4RR5LD', max_length=32),
        ),
    ]
