# Generated by Django 4.0.4 on 2022-06-06 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secret_key',
            field=models.CharField(default='ZFZK6LTTF43HZZSCOKO6AU3KWTXB5A5U', max_length=32),
        ),
    ]
