# Generated by Django 4.0.4 on 2022-06-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'mcq'), ('oneline', 'oneline')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='text_answer',
            field=models.CharField(default='mcq', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='answer_choosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
