# Generated by Django 4.0.4 on 2022-06-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_type_userrecord_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'mcq'), ('oneline', 'oneline')], max_length=10),
        ),
    ]
