# Generated by Django 4.0.3 on 2022-05-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_topic_score_to_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id',
            new_name='a_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='q_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='id',
            new_name='s_id',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='id',
            new_name='t_id',
        ),
    ]
