# Generated by Django 4.0.4 on 2022-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_topic_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='time_interval',
            field=models.IntegerField(default=0, help_text='Time Taken to Complete'),
        ),
    ]
