# Generated by Django 4.0.3 on 2022-05-06 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_rename_id_answer_a_id_rename_id_question_q_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_choosen', models.CharField(max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='score_to_pass',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
