# Generated by Django 4.0.4 on 2022-06-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestarted',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrecord',
            old_name='User',
            new_name='user',
        ),
    ]
