# Generated by Django 4.0.3 on 2022-05-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userrecord_rename_correct_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='answer_choosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
