# Generated by Django 4.0.4 on 2022-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userrecord_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='time_interval',
            field=models.IntegerField(help_text='Time Taken to Complete', null=True),
        ),
    ]
