# Generated by Django 4.0.3 on 2022-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_userrecord_answer_choosen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='answer_choosen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
