# Generated by Django 4.0.4 on 2022-05-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_time_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_started',
            options={'verbose_name_plural': 'Time_Started'},
        ),
    ]
