# Generated by Django 4.0.4 on 2022-05-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_time_started_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_started',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrecord',
            old_name='User',
            new_name='user',
        ),
    ]
