# Generated by Django 4.0.4 on 2022-05-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_time_started_starting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_started',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='userrecord',
            old_name='user',
            new_name='User',
        ),
    ]
