# Generated by Django 4.0.4 on 2022-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_user_time_started_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_started',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
