# Generated by Django 4.0.4 on 2022-05-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_time_started_starting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='time_interval',
        ),
    ]
